name: Build and Publish Installer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Replace '8.0.x' with your exact version if needed

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Installer
        run: msbuild /p:Configuration=Release Installer\Installer.vdproj

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: Installer\bin\Release\ROSE Login Manager Installer.msi  # Replace 'YourInstaller.msi' with the actual name of your MSI file
