name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

    - name: Publish
      run: dotnet publish -r win-x64 -c ${{ matrix.configuration }} --self-contained true -o ${{ github.workspace }}/publish

    - name: Upload Publish Directory
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ${{ github.workspace }}/publish
